#g++ -o Protonect Protonect.cpp -lfreenect2 -lopencv_core -lopencv_highgui #-I/usr/local/lib/libfreenect2/frame_listener_impl -I/usr/local/lib/libfreenect2/threading
#/usr/bin/c++   -DRESOURCES_INC -O2 -g -DNDEBUG -I/home/tamsformers/libfreenect2/examples/protonect/src/tinythread -I/usr/local/include/opencv -I/usr/local/include -I/home/tamsformers/libfreenect2/examples/protonect/../../depends/libusb/include/libusb-1.0 -I/home/tamsformers/libfreenect2/examples/protonect/../../depends/glfw_src/include -I/home/tamsformers/libfreenect2/examples/protonect/include -o Protonect.o -c Protonect.cpp
#/usr/bin/c++   -O2 -g -DNDEBUG Protonect.o -o Protonect -L/home/tamsformers/libfreenect2/examples/protonect/../../depends/libusb/lib -rdynamic /usr/local/lib/libfreenect2.so -lusb-1.0 /usr/local/lib/libopencv_videostab.so.2.4.10 /usr/local/lib/libopencv_ts.a -ldl -lm -lrt /usr/local/lib/libopencv_superres.so.2.4.10 /usr/local/lib/libopencv_stitching.so.2.4.10 /usr/local/lib/libopencv_contrib.so.2.4.10 /usr/local/lib/libopencv_nonfree.so.2.4.10 /usr/local/lib/libopencv_ocl.so.2.4.10 /usr/local/lib/libopencv_gpu.so.2.4.10 /usr/local/lib/libopencv_photo.so.2.4.10 /usr/local/lib/libopencv_objdetect.so.2.4.10 /usr/local/lib/libopencv_legacy.so.2.4.10 /usr/local/lib/libopencv_video.so.2.4.10 /usr/local/lib/libopencv_ml.so.2.4.10 /usr/local/lib/libopencv_calib3d.so.2.4.10 /usr/local/lib/libopencv_features2d.so.2.4.10 /usr/local/lib/libopencv_highgui.so.2.4.10 /usr/local/lib/libopencv_imgproc.so.2.4.10 /usr/local/lib/libopencv_flann.so.2.4.10 /usr/local/lib/libopencv_core.so.2.4.10 -lturbojpeg -lpthread /usr/local/lib/libglfw.so.3.0 -lX11 -lpthread -lXrandr -lXi -lXxf86vm -lrt -lm -lGL -lOpenCL -Wl,-rpath,/home/tamsformers/libfreenect2/examples/protonect/../../depends/libusb/lib:/home/tamsformers/libfreenect2/examples/protonect/lib:/usr/local/lib 

# Modified
#/usr/bin/c++ -std=c++11 -DRESOURCES_INC -O2 -g -DNDEBUG -I/usr/local/include/opencv -I/usr/local/include -I/usr/lib -I/usr/local/lib/ -o Protonect.o -c Protonect.cpp

/usr/bin/c++ -std=c++11 -O2 -g -DNDEBUG -I/usr/local/include/opencv -I/usr/local/include -I/usr/lib -I/usr/local/lib/ -o Protonect.o -c Protonect.cpp
/usr/bin/c++   -O2 -g -DNDEBUG Protonect.o -o Protonect  -L/usr/local/lib/libusb-1.0.so -rdynamic /usr/local/lib/libfreenect2.so  -lopencv_videostab -lopencv_ts -ldl -lm -lrt -lopencv_superres -lopencv_stitching -lopencv_contrib -lopencv_nonfree -lopencv_ocl -lopencv_gpu -lopencv_photo -lopencv_objdetect -lopencv_legacy -lopencv_video -lopencv_ml -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_imgproc -lopencv_flann -lopencv_core -lturbojpeg -lpthread -lglfw -lX11 -lpthread -lXrandr -lXi -lXxf86vm -lrt -lm -lGL -lOpenCL 
